export AUR_DIR=$HOME/Repositories/.aur
export ZSH="$HOME/.oh-my-zsh"
export ZSH_PLUGINS_DIR=/usr/share/zsh/plugins
export PATH="/home/alfarius/.local/bin:$PATH"
export PYTHONPATH=/usr/lib64/

autoload -Uz compinit promptinit
compinit
promptinit
prompt pure

plugins=(git docker docker-compose poetry)

zstyle ':completion:*:ssh:*' hosts off

source $ZSH/oh-my-zsh.sh
source $ZSH_PLUGINS_DIR/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZSH_PLUGINS_DIR/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

alias activate="source ./.venv/bin/activate"
